In [1]:
import numpy as np

In [2]:
0.5*(1+np.sqrt(5))

1.618033988749895

In [3]:
import tiles

In [4]:
tiles.PHI

1.618033988749895

In [5]:
np.pi

3.141592653589793

In [6]:
tiles.PHI_ROTATION

matrix([[ 0.30901699,  0.95105652],
        [-0.95105652,  0.30901699]])

In [7]:
np.cos(3)

-0.9899924966004454

In [8]:
tiles.rotation_matrix(np.pi)

matrix([[-1.0000000e+00, -1.2246468e-16],
        [ 1.2246468e-16, -1.0000000e+00]])

In [9]:
np.zeros((5,2))[0:2]

array([[0., 0.],
       [0., 0.]])

In [10]:
vertices = np.zeros((5,2))
vertices[0:2] = np.array([(1,2),(2,3)])
vertices

array([[1., 2.],
       [2., 3.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
for i in range(2,6):
    print(i)

2
3
4
5


In [12]:
np.array([1,0])*(tiles.rotation_matrix(tiles.PHI_ANGLE).T)

matrix([[0.30901699, 0.95105652]])

In [13]:
p = tiles.Pentagon((0,0),(1,0))

In [14]:
p.vertices

array([[ 0.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00],
       [ 1.30901699e+00,  9.51056516e-01],
       [ 5.00000000e-01,  1.53884177e+00],
       [-3.09016994e-01,  9.51056516e-01],
       [ 2.22044605e-16, -1.11022302e-16]])

In [15]:
import matplotlib.pyplot as plt

In [16]:
x = p.vertices[:,0]
y = p.vertices[:,1]

In [18]:
plt.plot(x,y)
plt.show()